"""Pure-Python foundations for QuickDraw's Branching Double DQN trainer."""

from .action_space import (
    BRANCH_SIZES,
    COMBAT_NAMES,
    MOVEMENT_NAMES,
    branches_from_joint_indices,
    epsilon_greedy_actions,
    gather_branch_values,
    greedy_actions,
    joint_indices_from_branches,
    masked_q_values,
)
from .network import DuelingBranchingQNetwork
from .exploration import LinearEpsilonSchedule
from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    LoadedCheckpoint,
    checkpoint_state_sha256,
    load_controller_checkpoint,
    save_controller_checkpoint,
)
from .llapi import (
    BASIC_BEHAVIOR_NAME,
    BasicTruncationMaskSideChannel,
    DirectReplayCollector,
    GreedyBDQActionSelector,
    LLAPIContractError,
    PendingDecision,
    ScheduledEpsilonGreedyBDQActionSelector,
    SeededEpsilonGreedyBDQActionSelector,
    TruncationMaskEvent,
    network_sha256,
    observation_sha256,
    read_action_masks,
    validate_action_masks,
    validate_basic_behavior_spec,
    validate_observation,
)
from .optimizer import (
    BDQOptimizationSettings,
    BDQOptimizerController,
    OptimizationStepResult,
)
from .replay import (
    REPLAY_MAX_ACCOUNTED_BYTES,
    ReplayBatch,
    ReplayBuffer,
    ReplayStorageMetrics,
    ReplayTransition,
    TorchReplayBatch,
)
from .targets import branch_double_dqn_targets, mean_branch_huber_loss

__all__ = [
    "BRANCH_SIZES",
    "COMBAT_NAMES",
    "MOVEMENT_NAMES",
    "DuelingBranchingQNetwork",
    "BDQOptimizationSettings",
    "BDQOptimizerController",
    "OptimizationStepResult",
    "CHECKPOINT_SCHEMA_VERSION",
    "LoadedCheckpoint",
    "checkpoint_state_sha256",
    "load_controller_checkpoint",
    "save_controller_checkpoint",
    "ReplayBatch",
    "ReplayBuffer",
    "ReplayStorageMetrics",
    "ReplayTransition",
    "REPLAY_MAX_ACCOUNTED_BYTES",
    "TorchReplayBatch",
    "BASIC_BEHAVIOR_NAME",
    "BasicTruncationMaskSideChannel",
    "DirectReplayCollector",
    "GreedyBDQActionSelector",
    "LLAPIContractError",
    "LinearEpsilonSchedule",
    "PendingDecision",
    "ScheduledEpsilonGreedyBDQActionSelector",
    "SeededEpsilonGreedyBDQActionSelector",
    "TruncationMaskEvent",
    "branch_double_dqn_targets",
    "branches_from_joint_indices",
    "epsilon_greedy_actions",
    "gather_branch_values",
    "greedy_actions",
    "joint_indices_from_branches",
    "masked_q_values",
    "mean_branch_huber_loss",
    "network_sha256",
    "observation_sha256",
    "read_action_masks",
    "validate_action_masks",
    "validate_basic_behavior_spec",
    "validate_observation",
]
